### ISSUE TITLE
admin/data only shows 100 layers

### ISSUE THREAD

**Issue by collinsbrennan** [emory-libraries-ecds/ATLMaps#10]
@jayvarner  the admin page to see all of the data layers only shows 100 layers. We now have over 100 layers and so I now can't see any layers after those first 100. I am trying to create a revised American Music Show layer, but can't delete the old layer.

**Comment by jayvarner** [comment]
Interesting, in the meantime, can you link the one you want to delete and I can take care of if for you?

**Comment by collinsbrennan** [comment]
Hey Jay,

It’s this one that should be erased https://atlmaps.org/layers/c7f60bf8

Thanks,
b

On May 29, 2018, at 11:20 PM, Jay Varner <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting, in the meantime, can you link the one you want to delete and I can take care of if for you?
